composition_controllers:
    resource:
        path: ../src/Composition/Infrastructure/Api/
        namespace: App\Composition\Infrastructure\Api
    type: attribute

analysis_controllers:
    resource:
        path: ../src/Analysis/Infrastructure/Api/
        namespace: App\Analysis\Infrastructure\Api
    type: attribute

exercise_controllers:
    resource:
        path: ../src/Exercise/Infrastructure/Api/
        namespace: App\Exercise\Infrastructure\Api
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults:
        _controller: nelmio_api_doc.controller.swagger_ui

app.swagger_json:
    path: /api/doc.json
    methods: GET
    defaults:
        _controller: nelmio_api_doc.controller.json
